title: LOLO' LINK

links:
  - Search Pages:
      - ICON: search.svg
      - 有道词典: https://dict.youdao.com
      - stack overflow: https://stackoverflow.com
      - V2EX: https://www.v2ex.com
      - https://zh.wikipedia.org
      - Pinterest: https://pinterest.com
      - 设计原型素材: https://resourceboy.com/
      - 在线小游戏: https://poki.com

  - AI:
      - ICON: robot.svg
      - Google AI Studio: http://aistudio.google.com/
      - DeepSeek: https://chat.deepseek.com/
      - 豆包: https://www.doubao.com/chat/
      - ChatGPT: https://chat.openai.com/
      - ImageFX: https://labs.google/fx/tools/image-fx/
      - Civitai: https://civitai.com/
      - Hugging Face: https://huggingface.co/
      - ComfyUI Examples: https://comfyanonymous.github.io/ComfyUI_examples/
      - PromptHero: https://prompthero.com/
      - SD Prompts: http://sd.firstool.online/
      - 长宽比例换算: https://www.shejidaren.com/examples/tools/aspect/index.html
      - 科学计数转十进制: https://iconvert.org/calculate/notation/2.3e-4

  - Node / JS / Web:
      - ICON: javascript.svg
      - NodeJS API: https://nodejs.cn/api/
      - ECMAScript 6: https://es6.ruanyifeng.com
      - fs-extra: https://juejin.cn/post/6844903641594216455
      - Day.js: https://day.js.org/zh-CN/
      - cheerio: https://github.com/cheeriojs/cheerio
      - Electron: https://www.electronjs.org/zh/docs/latest
      - Webpack: https://fakefish.github.io/react-webpack-cookbook/Introduction-to-Webpack.html
      - VUE: https://cn.vuejs.org/v2/guide/index.html
      - Element: https://element.eleme.cn/#/zh-CN/component/installation
      - Ant Design Vue: https://next.antdv.com/components/overview-cn
      - React: https://zh-hans.reactjs.org/docs/getting-started.html
      - Material-UI: https://mui.com/zh/getting-started/usage/
      - Semi Design: https://semi.design/zh-CN/start/overview
      - Fluent UI: https://developer.microsoft.com/zh-CN/fluentui?fabricVer=8#/controls/web
      - MDUI: https://www.mdui.org/docs/
      - https://getmdl.io
      - WeUI: https://github.com/Tencent/weui
      - Mithril.js: https://www.mithriljs.net/index.html
      - Xterm.js: https://xtermjs.org/
      - Auto-Animate: https://github.com/formkit/auto-animate

  - CSS:
      - ICON: css.svg
      - https://flukeout.github.io/
      - https://cssgrid-generator.netlify.app/
      - https://tobiasahlin.com/spinkit/
      - CSS Inspiration: https://chokcoco.github.io/CSS-Inspiration/#/
      - Dont need JS: https://github.com/you-dont-need/You-Dont-Need-JavaScript/blob/master/README-zh_CN.md
      - normalize.css: http://necolas.github.io/normalize.css/
      - pure.css: https://www.purecss.cn/
      - water.css: https://watercss.kognise.dev/
      - simple.css: https://simplecss.org/
      - sakura.css: https://oxal.org/projects/sakura/
      - primer.style: https://primer.style/

  - Unity:
      - ICON: unity.svg
      - Scripting API: https://docs.unity3d.com/cn/2021.3/ScriptReference/index.html
      - YAML Class ID Reference: https://docs.unity3d.com/cn/current/Manual/ClassIDReference.html
      - Rich Text Tags: https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/StyledText.html
      - link.xml Assemblies: https://docs.unity3d.com/2021.3/Documentation/ScriptReference/UnityEngine.AIModule.html
      - Define Directives: https://docs.unity3d.com/Manual/PlatformDependentCompilation.html
      - DOTween Doc: http://dotween.demigiant.com/documentation.php
      - EmmyLua Doc: https://emmylua.github.io
      - Unity Download Archive: https://unity3d.com/get-unity/download/archive
      - https://www.uwa4d.com
      - Unity Editor Icons: https://gist.github.com/masa795/5797164
      - Android Support Code: https://android.googlesource.com/platform/frameworks/support/+/79398eaefea45e61d839cf4e0534f0eafee70a09/v4/java/android/support/v4
      - Unity Built in Shaders: https://github.com/TwoTailsGames/Unity-Built-in-Shaders

  - C / C++ / C#:
      - ICON: cpp.svg
      - .NET API: https://docs.microsoft.com/zh-cn/dotnet/api/?view=netstandard-2.1
      - C++ 教程: https://www.runoob.com/cplusplus/cpp-environment-setup.html
      - LCUI: https://github.com/lc-soft/LCUI

  - Code:
      - ICON: terminal.svg
      - Hello GitHub: https://hellogithub.com/
      - Python 教程: https://docs.python.org/zh-cn/3/tutorial/index.html
      - PyTorch 教程: https://pytorch.apachecn.org
      - MacOS Anaconda PyTorch: https://blog.csdn.net/libing_zeng/article/details/96615716
      - Flarum 论坛框架: https://flarum.org/
      - gitignore: https://github.com/github/gitignore
      - KCP Protocol: https://github.com/skywind3000/kcp

  - NAS / VPS:
      - ICON: nas.svg
      - NameSilo: https://www.namesilo.com
      - Cloudflare: https://www.cloudflare.com/zh-cn/
      - Vultr: https://www.vultr.com
      - TencentCloud Lighthouse: https://cloud.tencent.com/product/lighthouse
      - 阿里云: https://www.aliyun.com/
      - Synology Archive Download: https://archive.synology.com/download
      - https://movie.douban.com/
      - https://www.themoviedb.org
      - 射手网 - 字幕: https://assrt.net/
      - 霸王龙压制组: https://t-rex.tzfile.com/
      - 6V电影网: https://www.6vdyy.com/
      - 电影港: https://www.dygang.cc/
      - 云盘电影: https://ypdy.cc/
      - 小白盘: https://www.xiaobaipan.com/
      - 单机游戏: https://www.aliyundrive.com/s/F15T9aT6wXu

  - Media Library:
      - ICON: media-library.svg
      - MusicFree: https://github.com/maotoumao/MusicFree
      - Soul Courier: https://soulcourier.com/index.php
      - K-POP MP3: http://ilkpop.com/index.xhtml
      - 八零电子书: https://txt80.cc/
      - 下载视频/封面/音频: https://snapany.com/
      - Clipchamp 剪视频: https://app.clipchamp.com/
      - 压缩图像: https://www.iloveimg.com/zh-cn
      - PNG 添加纯色背景: https://uutool.cn/png-bg/
      - 抠图: https://remove.photos/zh-cn/
      - 拼图 - Fotor: https://www.fotor.com/photo-editor-app/editor/basic
      - Shots: https://shots.so
      - 生成 Favicon: https://realfavicongenerator.net/
      - 调节音量大小: https://mp3cut.net/cn/change-volume/
      - 分离人声: https://vocalremover.org/zh/

  - Resources:
      - ICON: resource.svg
      - Google Fonts 中文版: https://www.font.im/
      - 爱给网/模型/资源: https://www.aigei.com/unity3d
      - Desire FX: https://www.desirefx.me/category/3d_models/
      - ByteDance IconPark: https://iconpark.oceanengine.com/official
      - 阿里矢量图标: https://www.iconfont.cn
      - macOSicons: https://macosicons.com/
      - https://fonts.google.com/icons
      - Material Icons Guide: https://developers.google.com/fonts/docs/material_icons
      - https://remixicon.com/
      - https://www.mixamo.com/
      - Steam Workshop Download: http://steamworkshop.download/download/view/1767287078
      - 世界名画: https://www.nbfox.com/

  - Online Tools:
      - ICON: toolbox.svg
      - 文件转换器: https://convertio.co/zh
      - Easing functions: https://easings.net
      - JSON Editor: https://jsoneditoronline.org/
      - 在线运行代码: https://www.bejson.com/runcode/lua/
      - 正则表达式解析器: https://codegen.bqrdh.com/regexper/
      - 时间戳转换: https://tool.lu/timestamp/
      - HexEd: https://hexed.it/
      - draw.io: https://app.diagrams.net/
      - Excalidraw: https://excalidraw.com/
      - 点点数据: https://app.diandian.com/rank/googleplay
      - 习题生成: https://dayin.page/
      - 自定义纸张: https://paperme.toolooz.com/
      - 租用海外手机号: https://sms-activate.io/
      - 国内外测试端口: https://tcp.ping.pe/
      - 企业信用信息公示: https://sh.gsxt.gov.cn/index.html

  - Bookmark:
      - ICON: bookmark.svg
      - 儿童睡前故事: https://beddystories.com/
      - 书栈网: https://www.bookstack.cn
      - Unity Cracking: https://appnee.com/unity
      - Unity Download: https://github.com/AlianBlank/download.unity.com
      - MacYY: https://www.macyy.cn/
      - MX Player Pro - OsitKP: https://www.423down.com/1300.html
      - MX Player Pro - Universal: https://www.yxssp.com/22999.html
      - PPT 模版: https://www.officeplus.cn/
      - VPS 部署 Hugo: http://www.shashun.site/post/first/
      - 移动游戏性能优化通用技法: https://www.cnblogs.com/timlly/p/10463467.html
      - 文件夹共享疑难解答: https://zhuanlan.zhihu.com/p/273532876
